"""002_review_enrichment_and_summaries

Revision ID: c5f1c3786bf9
Revises: 001_initial_schema
Create Date: 2026-09-07 04:11:06.534887

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c5f1c3786bf9"
down_revision: str | None = "001_initial_schema"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game_review_summaries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("review_type", sa.String(length=20), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column(
            "likes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "dislikes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("review_count_used", sa.Integer(), nullable=False),
        sa.Column("total_reviews_seen", sa.Integer(), nullable=False),
        sa.Column("input_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("prompt_version", sa.String(length=50), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("game_id", "review_type", name="uq_game_review_summary_game_type"),
    )
    op.create_index(
        op.f("ix_game_review_summaries_game_id"), "game_review_summaries", ["game_id"], unique=False
    )
    op.create_index(
        op.f("ix_game_review_summaries_id"), "game_review_summaries", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_game_review_summaries_input_fingerprint"),
        "game_review_summaries",
        ["input_fingerprint"],
        unique=False,
    )
    op.add_column("reviews", sa.Column("platform_id", sa.Integer(), nullable=True))
    op.add_column("reviews", sa.Column("source_url", sa.String(length=1024), nullable=True))
    op.add_column("reviews", sa.Column("content_hash", sa.String(length=64), nullable=True))
    op.add_column(
        "reviews",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index(op.f("ix_reviews_content_hash"), "reviews", ["content_hash"], unique=False)
    op.create_index(op.f("ix_reviews_platform_id"), "reviews", ["platform_id"], unique=False)
    op.create_foreign_key(
        None, "reviews", "platforms", ["platform_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "reviews", type_="foreignkey")
    op.drop_index(op.f("ix_reviews_platform_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_content_hash"), table_name="reviews")
    op.drop_column("reviews", "updated_at")
    op.drop_column("reviews", "content_hash")
    op.drop_column("reviews", "source_url")
    op.drop_column("reviews", "platform_id")
    op.drop_index(
        op.f("ix_game_review_summaries_input_fingerprint"), table_name="game_review_summaries"
    )
    op.drop_index(op.f("ix_game_review_summaries_id"), table_name="game_review_summaries")
    op.drop_index(op.f("ix_game_review_summaries_game_id"), table_name="game_review_summaries")
    op.drop_table("game_review_summaries")
    # ### end Alembic commands ###
